AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Fieldtrip Lambda - Fieldtrips, guided from the cloud.

Metadata:
  AWS::ServerlessRepo::Application:
    Name: 'Fieldtrip-Lambda'
    Description: Fieldtrips, guided from the cloud.
    Author: Kit McCormick
    SpdxLicenseId: Beerware
    LicenseUrl: license.txt
    ReadmeUrl: README.md
    Labels: ['SMS', 'travel', 'pinpoint', 'lambda', 'nodejs']
    HomePageUrl: https://github.com/gumballsoftware/fieldtrip-lambda
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/gumballsoftware/fieldtrip-lambda

Parameters:
  ApplicationId:
    Type: String
    Default: 'PinpointApplicationId'
    Description: (Required) Pinpoint application ID (project ID)
    AllowedPattern: ^[A-Za-z0-9-]+$
    ConstraintDescription: 'Required parameter.'

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  smsResponderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: smsResponderFunction/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Environment:
        Variables:
          ApplicationId: !Ref ApplicationId
      Policies:
      - Statement:
        - Sid: PinpointAccess
          Effect: Allow
          Action:
          - mobiletargeting:*
          Resource: '*'
        - Sid: PinpointSNStopic
          Effect: Allow
          Action:
            - sns:*
          Resource: !Ref smsResponderIncomingSNSTopic
      Events:
        incomingSNS:
          #SNS queue where Pinpoint sends incoming text messages
          Type: SNS
          Properties:
            Topic:
              Ref: smsResponderIncomingSNSTopic
  smsResponderIncomingSNSTopic:
    Type: 'AWS::SNS::Topic'

Outputs:
  smsResponderFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt smsResponderFunction.Arn
  smsResponderFunctionIamRole:
    Description: "Implicit IAM Role created for function"
    Value: !GetAtt smsResponderFunctionRole.Arn
